version: '3.9'

services:
  django:
    labels:
      - "traefik.http.routers.django.entrypoints=websecure"
      - "traefik.http.routers.django.tls=true"
      - "traefik.http.routers.django.middlewares=security-headers@file,compression@file"

  mailhog:
    labels:
      - "traefik.http.routers.mailhog.tls=true"
      - "traefik.http.routers.mailhog.middlewares=security-headers@file,compression@file"

  flower:
    labels:
      - "traefik.http.routers.flower.tls=true"
      - "traefik.http.routers.flower.middlewares=security-headers@file,compression@file"

  # docs:
  #   labels:
  #     - "traefik.http.routers.flower.tls=true"
  #     - "traefik.http.routers.flower.middlewares=security-headers@file,compression@file"

# For Traefik 3.0
  # postgres:
  #   ports: !reset []
  #   expose:
  #     - '5432'
  #   labels:
  #     - "traefik.enable=true"
  #     # - "traefik.tcp.routers.postgres.rule=HostSNI(`*`)"
  #     # - "traefik.tcp.routers.postgres.tls=false"
  #     # - "traefik.tcp.routers.postgres.tls.options=default"
  #     - "traefik.tcp.routers.postgres.rule=HostSNI(`${DOMAIN}`)"
  #     - "traefik.tcp.routers.postgres.entrypoints=postgres"
  #     - "traefik.tcp.routers.postgres.service=postgres@docker"
  #     - "traefik.tcp.routers.postgres.tls=true"
  #     - "traefik.tcp.services.postgres.loadBalancer.server.port=5432"
