# Generated by Django 4.2.4 on 2023-09-03 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="order_in_packs",
            field=models.BooleanField(
                default=False, verbose_name="Заказывают в упаковках?"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="volume",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Объем, мл. (Вес, гр.)"
            ),
        ),
        migrations.CreateModel(
            name="CustomerProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название товара"),
                ),
                (
                    "vendor_code",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Артикул"
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="orders.customer",
                        verbose_name="Клиент",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_products",
                        to="orders.product",
                        verbose_name="Товар из внутренней матрицы",
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар клиента",
                "verbose_name_plural": "Товары клиентов",
                "db_table": "customer_products",
                "ordering": ("id",),
            },
        ),
        migrations.AlterField(
            model_name="customerorder",
            name="products",
            field=models.ManyToManyField(
                related_name="customer_orders",
                to="orders.customerproduct",
                verbose_name="Товары в заказе",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="products",
            field=models.ManyToManyField(
                related_name="orders",
                through="orders.ProductInOrder",
                to="orders.customerproduct",
                verbose_name="Товары в заказе",
            ),
        ),
        migrations.AlterField(
            model_name="productinorder",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="orders.customerproduct"
            ),
        ),
    ]
