# Generated by Django 4.2.4 on 2023-09-04 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_customer_order_in_packs_product_volume_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerproduct",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="customer_products",
                to="orders.product",
                verbose_name="Товар из внутренней матрицы",
            ),
        ),
    ]
