# Generated by Django 4.2.4 on 2023-09-04 17:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_alter_customerproduct_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="vendor_code",
            field=models.CharField(max_length=255, unique=True, verbose_name="Артикул"),
        ),
    ]
