# Generated by Django 4.2.4 on 2023-09-05 12:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0004_alter_product_vendor_code"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customerproduct",
            old_name="product",
            new_name="base_product",
        ),
    ]
